#!/bin/sh -e

CMD_DIR=$(dirname "$0")
. "${CMD_DIR}/sdk.sh"

podman run \
	--rm \
	-it \
	-v ~/.cache/ccache:/root/.cache/ccache \
	-e CCACHE_DIR=/root/.cache/ccache \
	-v "$(pwd)":/workspace \
	-w /workspace \
	${BUILD_IMAGE}
