#!/bin/sh -e

CMD_DIR=$(dirname "$0")
RELOADABLE=OFF
. "${CMD_DIR}/../common.sh"

OUT=".build/msvc-wine/${BUILD_TYPE}"

[ -f "${OUT}/build.ninja" ] || "${CMD_DIR}/configure"
exec cmake --build "${OUT}"
